blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed
app_name = 'blog'


urlpatterns = [
               # post views
               path('', views.post_list, name='post_list'),
               path('<int:year>/<int:month>/<int:day>/<slug:post>/',
                       views.post_detail,
                       name='post_detail'),
               path('<int:post_id>/share/',views.post_share, name='post_share'),
               path('search/', views.post_search, name='post_search'),
               path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
               path('feed/', LatestPostFeed(), name='post_feed'),
]

kingzblog/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns =[
        path('admin/', admin.site.urls),
        path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
  def get_queryset(self):
    return super(PublishedManager,
    self).get_queryset()\
          .filter(status='published')

class Post(models.Model):
  STATUS_CHOICES = (('draft', 'Draft'),('published', 'Published'),)
  title = models.CharField(max_length=250)
  slug = models.SlugField(max_length=250,unique_for_date='publish')
  author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
  body = models.TextField()
  tags = TaggableManager()
  publish = models.DateTimeField(default=timezone.now)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
  objects = models.Manager()
  published = PublishedManager()
  class Meta:
    ordering = ('-publish',)

  def __str__(self):
    return self.title


  def get_absolute_url(self):
    return reverse('blog:post_detail',
                args=[self.publish.year,
                 self.publish.month,
                 self.publish.day,
                 self.slug])


class Comment(models.Model):
   post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
   name = models.CharField(max_length=80)
   email = models.EmailField()
   body = models.TextField()
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)
   active = models.BooleanField(default=True)
  
   class Meta:
       ordering = ('created',)
  
   def __str__(self):
       return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment



class EmailPostForm(forms.Form):
   name = forms.CharField(max_length=25)
   email = forms.EmailField()
   to = forms.EmailField()
   comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
   class Meta:
       model = Comment
       fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
   query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage,\
PageNotAnInteger
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm,SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank



#Create your views here.

# def post_list(request, tag_slug=None):
#   object_list = Post.published.all()
#   tag = None

# f tag_slug:
# #     tag = get_object_or_404(Tag, slug=tag_slug)
# #     object_list = object_list.filter(tags__in=[tag])#   i

#   paginator = Paginator(object_list,)
#   page = request.GET.get('page')
#   try:
#     posts = paginator.page(page)
#   except PageNotAnInteger:
#     posts = paginator.page(1)
#   except Emtypage:
#     post = paginator.page(paginator.num_pages)
#   return render(request, 'blog/post/list.html',{'page':page,'posts':post,'tag':tag})


def post_list(request, tag_slug=None):
  object_list = Post.published.all()
  tag= None

  if tag_slug:
    tag = get_object_or_404(Tag, slug=tag_slug)
    object_list = object_list.filter(tags__in=[tag])   

  paginator = Paginator(object_list, 3) # 3 posts in each page
  page = request.GET.get('page')
  try:
     posts = paginator.page(page)
  except PageNotAnInteger:
    # If page is not an integer deliver the first page
    posts = paginator.page(1)
  except EmptyPage:
      # If page is out of range deliver last page of results
      posts = paginator.page(paginator.num_pages)
  return render(request,
                'blog/post/list.html',
                {'page': page,'posts': posts, 'tag': tag})




# def post_list(request):
#   posts = Post.published.all()
#   return render(request,
#   'blog/post/list.html',
#   {'posts': posts})

def post_detail(request, year, month, day, post):
  post = get_object_or_404(Post, slug=post,
                                 status='published',
                                 publish__year=year,
                                 publish__month=month,
                                 publish__day=day)
  post_tags_ids = Post.tags.values_list('id',flat=True)
  similar_Posts = Post.published.filter(tags__in=post_tags_ids)\
                                      .exclude(id =Post.id)
  similar_Post = similar_posts.annotate(same_tags=Count('tags'))\
                      .order_by('-same_tags",-publish')[:4]     
  return render(request,
                'blog/post/detail.html',
                {'post': post, 'comments': new_comment, 'comment_form': comment_form,'similar_post': similar_Posts})

def post_share(request, post_id):
  post = get_object_or_404(Post, id=post_id, status='published')
  sent = False
   # Retrieve post by id


  if request.method == 'POST':
    form = EmailPostForm(request.POST)
    if form.is_valid():
           # Form fields passed validation
           cd = form.cleaned_data
           post_url = request.build_absolute_uri(post.get_absolute_url())
           subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
           message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
           send_mail(subject,message, 'admin@myblog.com',[cd['to']])
           sent = True
           # ... send email
  else:
       form = EmailPostForm()
  return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent':sent})                             

class PostListView(ListView):
  queryset = Post.published.all()
  context_object_name = 'posts'
  paginate_by = 3
  template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
   post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
   # list of active comments for this post
   comments = post.comments.filter(active=True)

   new_comment = None
   if request.method == 'POST':
         comment_form = CommentForm(data=request.POST)
         if comment_form.is_valid():
           # Create Comment object but don't save to database yet
           new_comment = comment_form.save(commit=False)
           # Assign the current post to the comment
           new_comment.post = post
           # Save the commnet to the database
           new_comment.save()
   else:
       comment_form = CommentForm()
   return render(request,
               'blog/post/detail.html',
               {'post': post, 'comments':comments,'new_comments':new_comment,'comment_form': comment_form})


def post_search(request):
  form = SearchForm()
  query = None
  results = []
  if 'query' in request.GET:
    form = SearchForm(request.GET)
    if form.is_valid():
      query = form.cleaned_data['query']
      # results = post.objects.annotate(search=searchVector('title','body'),).filter(search=query)
      search_vector = SearchVector('title','body')
      search_query = SearchQuery(query)
      results = Post.objects.annotate(search =search_vector,rank = SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')
  return render(request, 'blog/post/search.html',{'form':form,'query':query,'results':results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
   <title>{% block title %}{% endblock %}</title>
   <link rel="stylesheet" href="{% static  'css/blog.css' %}">
</head>
<header>
  <div class="first">
    <div class="tap">
      <strong><a href="#"><img width="100" heigh="200"src="https://cdn-icons-png.flaticon.com/512/60/60736.png"/</a></strong>
    </div>
    <ul class="child">
      <li class="box"><a href="http://127.0.0.1:8000/blog/" class="class-1">Article</a></li>
      <li class="box"><a href="#" class="class-2">Books</a></li>
      <li class="box"><a href="#" class="class-3">workshop</a></li>
      <li class="box"><a href="#" class="class-4">confrence</a></li>
      <li class="box"><a href="#" class="class-5">membership</a></li>
    </ul>
    <div class="top"><button class="pig"><a href="http://127.0.0.1:8000/blog/search/" class="link">search</a></button></div>
    <div class="topnav">
     <!-- <input type="text" placeholder= "&#128269 Search article"> -->
    </div>
  </div>
</header>
<section class="second">
  <div class="container">
    <button class="box-1">premierleauge</button>
    <button class="box-2">seria A</button>
    <button class="box-3">laliga</button>
    <button class="box-4">budesligs</button>
    <button class="box-5">ligue 1</button>
    <button class="box-6">champoinship</button>
    <button class="box-7">wrestling</button>
    <button class="box-8">kickboxing</button>
    <button class="box-9">boxing</button>
    <button class="box-10">UFC</button>
    <button class="box-11">EFC</button>
    <button class="box-12">olympic</button>
    <button class="box-13">formular 1</button>
  </div>
</section>
<body>
  <div id="content">
    <div class="doma">
    {% block content %}
    </div>
    {% endblock %}
    <div class="main">
      <div class="child-1">
        <a href="#" class="anchor">Realmadrid Champions</a>
        <p class="role">Realmadrid the most highest in all the club that has won the champions leauge trophy even back to back, which has never been done by any club.</p>
        <button class="button"><a href="#" class="time">Explore Accesible matches played</a></button>
      </div>
      <div class="child-2">
        <a href="#" class="rem">Manchester United highest trophies</a>
        <p class="ram">Manchester United is the highest in all football club in england when it comes to trophies won by the football clubs</p>
        <button class="button-1"><a href="#" class="jet">Explore All Their matches played</a></button>
      </div>
      <div class="child-3">
        <a href="#" class="gen">Arsenal football club emerge as the winner of premier leauge<a/>
        <p class="fam">Arsenal football club is the only football club that had an invicible run during their campain in premier leauge.</p>
        <button class="button-2"><a href="#" class="fom">Explore All their matches played.</a></button>
      </div>
    </div>
  </div>
  <div id="sidebar">
  </div>
  <footer>
    <div class="last">
      <h4>BROWSE ALL THE CHAMPIONS LEAUGE MANAGERS WITH TROPHY</h4>
      <ul class="gogo">
        💎<li><a href="#"class="vomp">carlo-Anceloti</a></li>
        💎<li><a href="#"class="vomp">Bob paisley</a></li>
        <li>💎<a href="#"class="vomp">zinedine zidane</a></li>
        <li>💎<a href="#"class="vomp">jose villalonga</a></li>
        <li>💎<a href="#"class="vomp">Luis Carniglia</a></li>
        <li>💎<a href="#"class="vomp">Bela Guttmann</a></li>
        <li>💎<a href="#"class="vomp">Helenio Herrera</a></li>
        <li>💎<a href="#"class="vomp">migule munoz</a></li>
        <li>💎<a href="#"class="vomp">Nereo Rocco</a></li>
        <li>💎<a href="#"class="vomp">stefan kovacs</a></li>
        <li>💎<a href="#"class="vomp">dettmar cramer</a></li>
        <Ii>💎<a href="#"class="vomp">clough</a></li>
        <li>💎<a href="#"class="vomp">Ernest happle</a></li>
      </ul>
      <P>With a commitment to quality content for the design community.
        Founded by Vitaly Friedman and Sven Lennartz. 2006–2023.
        Smashing is proudly running on Netlify.</P>
    </div>
  </footer>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %} 
{% block title %}
<!-- {{ post.title }}{% endblock %} -->
{% block content %}
<div class="detail">
   <h1 class="title">{{ post.title }}</h1>
   <p class="tip">
   <!-- Published {{ post.publish }} by {{ post.author }} -->
 </p>
 {{ post.body|markdown }}
 <p>
</div>
   <a href="{% url "blog:post_share" post.id %}">
   Share this post
   </a>
</p> 
<h2>similar posts</h2>
      {% for post in similar_post %} 
            <p>
               <a href="{{post.get_absolute_url}}">{{post.title}}</a>
            </p>
      {% empty %} 
            There are no similiar post yet.
      {% endfor %} 
{% with comments.count as total_comments%}
<h2>
   {{ total_comments}} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
   <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name}} 
      {{ comment.created }}
   </p>
   {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>there are no comments yet.</p>
{% endfor %} 
{% if new_comment %} 
<h2>your comment has been added.</h2>
{% else %} 
<h2>Add a new comment</h2>
<form action="." method="post">
   {{ comment_form.as_p }} 
   {% csrf_token %} 
   <p><input type="submit" value="Add comment"> </p>
</form>
{% endif %} 
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_post %} 
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title}}</a>
  </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %} 
{% block title %} My Blog {% endblock %}

{% block content %}
{% if tag %}
<h2>post tagged with "{{ tag.name }}"</h2>
{% endif %} 
{% for post in posts %}
<div class="article">
    <h2 class="angof">
        <p>{{post.author}} wrote</p>
        <a href="{{post.get_absolute_url}}">
            {{post.title}}
        </a>

            <p class="tags">
                Tags:
                {% for tag in post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{tag.name}}
                    </a>
                {% if not forloop.last %}, {% endif %} 
                {% endfor %} 
            </p>
           
        </h2>
        <div class="yam">
        <p class="date">
            {{ post.body|markdown|truncatewords_html:90 }}
            <a href="{{post.get_absolute_url}}">Read more...</a>
        </p>
        </div>
    </div>
    {% endfor %}
         {% include "pagination.html" with page=posts %}
    {% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}search{% endblock %} 

{% block content %}
    {% if query %} 
        <hi>Post containing "{{ query }}"</hi>
        <h3> {% with results.count as total_results %}Found {{ total_results }} results{{ total_result|pluralize}} 
          {% endwith %} 
        </h3>
        {% for post in results %} 
        <h4><a href="{{ post.get_absolute_url}}">{{ post.title}}</a></h4>
        {{post.body|truncatewords:5 }} 
        {% empty %} 
            <p>There are no result for query.</p>
        {% endfor %} 
            <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
        {{ form.as_p }}
        <input type="submit" value="search">
    </form>
    {% endif %} 
{% endblock %} 

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Search {% endblock %}

{% block content %}
    {% if query %}
        <h1>Post containing "{{ query }}"</h1>
        <h3>{% with results.count as total_results %}
            Found {{ total_results }} result {{total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h4>
            {{post.body|truncatewords:5 }}
        {% empty %}  
            <p>There are no results for query.</p>
        {% endfor %}    
            <p><a href="{% url 'blog:post_search' %}">Search again</a></p>  
    {% else %}  
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>  
    {% endif %}
{% endblock %}  

<!-- {% for field in form %}
<div class>
{{ field.errors }}
{{ field.label_tag }} {{ field }}
</div>
{% endfor %} -->

blog/templates/pagination.html
<!-- <div class="pagination">
  <span class="step-links">
      {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
          Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div> -->






<div class="pagination">
  <span class="step-links">
      {% if page.has_previous %}
      <span class="previous">
      <a class="case" href="?page={{ page.previous_page_number }}">
      <div class="king">
       < 
       </div>
        </a>
      </span>

      {% endif %}
      <span class="current">
        <a href="http://127.0.0.1:8000/blog/?page=1">
       <div class="case">
        <div class="king">
          {{1}} 
        </div>
       </div>
       </a>
      </span>
      <span>
      <a href="http://127.0.0.1:8000/blog/?page=2">
        <div class="case">
         <div class="king">
          {{2}}
          <!-- {{ page.paginator.num_pages }} -->
         </div>
        </div>
      </a>
     </span>
     <span>
      <a href="http://127.0.0.1:8000/blog/?page=2">
        <div class="case">
         <div class="king">
          {{3}}
          <!-- {{ page.paginator.num_pages }} -->
         </div>
        </div>
      </a>
     </span>
     <span>
      <a href="http://127.0.0.1:8000/blog/?page=2">
        <div class="case">
         <div class="king">
          {{4}}
          <!-- {{ page.paginator.num_pages }} -->
         </div>
        </div>
      </a>
     </span>
     <span>
      <a href="http://127.0.0.1:8000/blog/?page=2">
        <div class="case">
         <div class="king">
          {{5}}
          <!-- {{ page.paginator.num_pages }} -->
         </div>
        </div>
      </a>
     </span>
    {% if page.has_next %}
    <span class="next">
      <a class="case" href="?page={{ page.next_page_number }}">
      <div class="king">
        >
      </div>
    </a>
    </span>
    {% endif %}
  </span>
</div>